#+title: How To Write

* Engine
** Introduction
This manual is written using the
[[https://orgmode.org][=org-mode= markup language]].

You can find some cheatsheets for org's markup you can checkout
- https://orgmode.org/quickstart.html
- http://xahlee.info/emacs/emacs/emacs_org_markup.html

Please notice that for this manual to build you will need
a recent version of emacs, at least newer than *Emacs 27*.
You probably can install it from [[https://snapcraft.io/emacs][the snapstore]] if you are using
a supported distribution.

*** Installing a minimal emacs version locally

In case you are having some problems installing emacs
and you just want to get a minimal emacs version to build the pages,
consider adapting this script

#+begin_src sh :eval no
set -eu

url="https://github.com/emacs-mirror/emacs/archive/refs/tags/emacs-28.0.90.tar.gz"

mkdir -p ./emacs
wget $url -O - | gunzip |  tar xvf - -C ./emacs --strip-components=1

sudo apt-get install \
     libxml2-dev \
     gnutls-dev

cd ./emacs

./autogen.sh
./configure \
    --with-x-toolkit=no \
    --with-xml2 \
    --with-xpm=ifavailable \
    --with-gif=ifavailable \
    --with-tiff=ifavailable \
    --with-gnutls=ifavailable

make -j
#+end_src

This script installs on a debian-based system the library =xml2= and =gnutls=
and downloads and builds emacs 28 in the current directory.

You can use this emacs binary by writing a =config.mk= file with the following contents

#+begin_src make
EMACS_BIN = $PWD/emacs/src/emacs
#+end_src



** Math
Just use latex as if you were in latex
$$\int \sum$$
and you can also use equations

\begin{equation}
\label{eqseq}
\hat{H} \psi = E \psi
\end{equation}
and references work too \ref{eqseq}.

** Bibliography

In order to use a bibtex file in a page,
you have to add it with the
#+begin_src org
bibliography:group.bib
# or
bibliography:./path-to-your-bib-file.bib,other-file.bib
#+end_src

and add citations like =cite:&yourcite=, for instance
[[cite:&al2017properties;&gruneis2017perspective]].


Here an example of the rendered bibliography of the citations made up here.
*** Literature
bibliography:group.bib
*** More information
You can find more information in videos like [[https://www.youtube.com/watch?v=3u6eTSzHT6s][this]] by the
[[https://github.com/jkitchin/org-ref][org-ref]] author.


** Src blocks
If you want to write some code blocks, the equivalent of markdown's
#+begin_src markdown
```python
def fun():
  pass
```
#+end_src
in org is
#+begin_src org
,#+begin_src python
def fun():
    pass
,#+end_src
#+end_src

and it renders like:

#+begin_src python
def fun():
    pass
#+end_src


* Test locally

To build locally just make
#+begin_src sh
make publish
#+end_src

You can also serve the pages to simulate how they will be deployed
using
#+begin_src sh
make serve
#+end_src
and open the url in your browser http://127.0.0.1:8888.

You can also combine both by doing
#+begin_src sh
make publish serve
#+end_src
periodically and refreshing your browser.
