:PROPERTIES:
:ID: Amplitudes
:END:
#+title: Amplitudes
# #+OPTIONS: toc:nil

* Brief description

=Amplitudes= are a set of tensors, usually containing the closed-shell
singles $t_i^a$ and the doubles $t_{ij}^{ab}$ amplitudes, that solve
the employed coupled-cluster amplitude equation.
The canonical closed-shell coupled-cluster correlation energy is given by
\begin{equation}
  E_\mathrm{cc}
  = \frac12 \sum_{abij}
    \left(t^{ab}_{ij} + t^a_i t^b_j\right)
    \left(2V^{ij}_{ab} - V^{ji}_{ab}\right).
\end{equation}
Note, that the closed-shell doubles amplitudes are symmetric with respect
to interchanging left and right inidices $t^{ab}_{ij}=t^{ba}_{ji}$.

* Specification

The =Amplitudes= parametrize the correlated wave function $|\Psi\rangle$
using the coupled-cluster Ansatz
\begin{equation}
  | \Psi \rangle = e^{\hat T} | \Phi \rangle,
\end{equation}
where $|\Phi\rangle$ denotes the single Hartree--Fock slater determinant.
The cluster operator $\hat T = \hat T_1 + \hat T_2 + \ldots$ is
expanded in increasing number of excitation levels. The single and
double exciation parts of the cluster operator are given by
\begin{eqnarray}
  \hat T_1 = \sum_{ai} t^a_i \hat\tau^a_i, \\
  \hat T_2 = \sum_{abij} t^{ab}_{ij} \hat\tau^{ab}_{ij},
\end{eqnarray}
where $\hat \tau^{a\ldots}_{i\ldots} = \hat c^\dagger_a\ldots \hat c_i\ldots$
denotes the exciation operator.
The coefficients $t^a_i$, $t^{ab}_{ij}$, $\ldots$ are called coupled-cluster
=Amplitudes=.
The =Amplitudes= are generated by the [[id:CoupledCluster][=CoupledCluster=]]
algorithm by solving the amplitude equation of the employed
coupled-cluster method, described therein.

* Literature
bibliography:../group.bib


