:PROPERTIES:
:ID: Amplitudes
:END:
#+title: Amplitudes
# #+OPTIONS: toc:nil

* Brief description

=Amplitudes= are a set of tensors, usually containing the closed-shell
singles $t_i^a$ and the doubles $t_{ij}^{ab}$ amplitudes, that solve
the employed coupled-cluster amplitude equation.
The canonical closed-shell coupled-cluster correlation energy is given by
\begin{equation}
  E_\mathrm{cc}
  = \frac12 \sum_{abij}
    \left(t^{ab}_{ij} + t^a_i t^b_j\right)
    \left(2V^{ij}_{ab} - V^{ji}_{ab}\right).
\end{equation}
Note, that the closed-shell doubles amplitudes are symmetric with respect
to interchanging left and right inidices $t^{ab}_{ij}=t^{ba}_{ji}$.

* Specification

The =Amplitudes= parametrize the correlated wave function $|\Psi\rangle
using the coupled-cluster Ansatz
\begin{equation}
  | \Psi \rangle = e^{\hat T} | \Phi \rangle,
\end{equation}
where $|\Phi\rangle denotes the single Hartree--Fock slater determinant.
The cluster operator $\hat T = \hat T_1 + \hat T_2 + \ldots$ is
expanded in increasing number of excitation levels. The single and
double exciation parts of the cluster operator are given by
\begin{eqnarray}
  \hat T_1 = \sum_{ai} t^a_i \hat\tau^a_i, \\
  \hat T_2 = \sum_{abij} t^{ab}_{ij} \hat\tau^{ab}_{ij},
\end{eqnarray}
where $\tau^{a\ldots}_{i\ldots} = \hat c^\dagger_a\ldots \hat c_i\ldots$
denotes the exciation operator.
The coefficients $t^a_i$, $t^{ab}_{ij}$, $\ldots$ are called coupled-cluster
=Amplitudes=.
They are found by projecting the stationary Schrödinger equation for the
coupled-cluster Ansatz $E|\Psi\rangle = \hat H|\Psi\rangle$
on $\langle \Phi|e^{-\hat T}$.
The resulting over-determined set of equations is truncated at the
same level as the cluster-operator $\hat T$, giving as many equations
as there are coefficients in $\hat T$.
The =Amplitudes= are generated by the [[id:CoupledCluster][=CoupledCluster=]]
algorithm by solving the amplitude equation of the employed
coupled-cluster method, described below:

** =Ccsd= and =CcsdReference=
The cluster-operator is truncated containing only single and double
excitations. The projections on the singly and doubly excited
slater-determinants $\langle \Phi^a_i|$ and $\langle \Phi^{ab}_{ij}|$ give
\begin{align}
  \big\langle \Phi^{a}_{i} \big| e^{-\hat T} \hat H e^{\hat T}
    \big| \Phi \big\rangle &= 0 \quad \forall ai, \\
  \label{eqn:t2}
  \big\langle \Phi^{ab}_{ij} \big| e^{-\hat T} \hat H e^{\hat T}
    \big| \Phi \big\rangle &= 0 \quad \forall abij.
\end{align}
The above equations expand to a finite set of a few dozens of, in general,
non-linear algebraic contractions of $t^a_i$ and $t^{ab}_{ij}$ with
$\varepsilon_p$ and $V^{pq}_{sr}$. See cite:shavitt_many-body_2009 for
a text-book introduction of the original works of
cite:coester_short-range_1960 and cite:cizek_use_1969.

** =Drccd=
The direct-ring coupled-cluster doubles (drccd) method only the double
excitation part of the cluster-operator is taken. From
the doubles amplitude equations in Eq. (\ref{eqn:t2}) only
those contractions are considered where pairs of particle and hole
contractions originate and terminate on the same vertex, respectively,
forming direct-rings in the diagrammatic notation.
Only five terms remain in a canonical calculation and they read
\begin{equation}
  \Delta^{ab}_{ij} t^{ab}_{ij}
  + V^{ab}_{ij}
  + V^{kb}_{cj} t^{ac}_{ik}
  + V^{al}_{id} t^{db}_{lj}
  + V^{kl}_{cd} t^{ac}_{ik} t^{db}_{lj} = 0 \quad \forall abij,
\end{equation}
with
$\Delta^{ab}_{ij} = \varepsilon_a+\varepsilon_b-\varepsilon_i-\varepsilon_j$
and where a sum over all indices that occurr only on the right-hand-side
is implied. These terms are the dominant terms of coupled-cluster singles
doubles in the hight-density limit cite:gell-mann_correlation_1957.
The direct correlation contribution of the =Drccd= method
$\sum_{abij} 2t^{ab}_{ij}V^{ij}_{ab}$ gives Random Phase Approximation (RPA),
the remaining exchange contribution is often termed Second Order
Screened Exchange (SOSEX) correction
cite:freeman_coupled-cluster_1977,gruneis_making_2009.
See cite:Furche2008,Furche_2018 for a review on the RPA and its corrections,
as well as cite:macke_uber_1950,pines_collective_1952 for the
original work on the RPA.


* Literature
bibliography:../group.bib


