#+title: How to run =Cc4s= calculations?

#+macro: CV [[id:CoulombVertex][=CoulombVertex=]]

* Introduction

In this tutorial we explain all steps necessary to perform a  =Cc4s= calculation
on the level of CCSD(T) theory for a simple test system.
The test system corresponds to a periodic rhomobohedral boron nitride crystal.
All required =Cc4s= input files have been created using the =VASP= interface.

=Cc4s= calculations are controlled by a YAML input file, which is called =cc4s.in= in the present tutorial.
This input file consists of a list of calls to algorithms with input arguments and output objects.
Here, we will walk you through all employed algorithms used to compute the CCSD(T) correlation energy.
However, if you want to skip the detailed  explanations below and proceed directly to performing
CCSD(T) calculations, you might as well download the complete =cc4s.in= file (here, TODO add link).

* Prerequisites

The following files are needed to reproduce all calculations of this tutorial.

- A working binary of =Cc4s= obtained by [[id:GettingStarted][compiling the code]]
- A set of input files generated by the =VASP= [[id:VaspInterface][interface]] and can be downloaded (TODO add link here)
  + $\Gamma^{pG}_{q}$ :  =CoulombVertex.yaml=, =CoulombVertex.dat=
  + $\epsilon_{p}$ : =EigenEnergies.yaml=, =EigenEnergies.dat=
  + $\vec G$ : =GridVectors.yaml=, =GridVectors.dat=
  + $\tilde{v}(\vec G)$ : =CoulombPotential.yaml=, =CoulombPotential.dat=
  + $\delta^{ab}_{ij}$ : =DeltaPPHH.yaml=, =DeltaPPHH.dat=
  + $\delta_{ij}$ : =DeltaHH.yaml=, =DeltaHH.dat=
  + $U_F^G$ : =CoulombVertexSingularVectors.yaml=, =CoulombVertexSingularVectors.dat=
  + $\epsilon_{ij}$ : =Mp2PairEnergies.yaml=, =Mp2PairEnergies.dat=

For the following example we assume that all input files listed above and the =cc4s.in= file
are located in the same directory.
The =cc4s.in= YAML input file is described in the following section in detail.

* Coupled cluster singles and doubles theory calculations

We start this tutorial by taking the first steps in =Cc4s= needed to compute the CCSD correlation energy.
For this purpose essential data files have to be read from disk using the =TensorReader= algorithm.
This aglorithm can be executed employing the following  =cc4s.in= YAML input which controls =Cc4s=

#+begin_src yaml
- name: TensorReader
  in:
    fileName: "CoulombVertex.yaml"
  out:
    tensor: CoulombVertex
#+end_src

The above call to the [[id:TensorReader][TensorReader]] algorithm reads the
*CoulombVertex.yaml* file that contains all meta-information associated with the
{{{CV}}} tensor in a human-readable format.
=Cc4s= will follow the link in *CoulombVertex.yaml* specified by =data:= to *CoulombVertex.dat* and read all numerical data of
the corresponding {{{CV}}} tensor from disk.
The output of [[id:TensorReader][TensorReader]] algorithm is the {{{CV}}} tensor object, which can
be used as input for all subsequent =Cc4s= algorithms.

In addition, we use =Cc4s= to read the *EigenEnergies.yaml* and
*EigenEnergies.dat* files by including the following [[id:TensorReader][TensorReader]] call in =cc4s.in=
#+begin_src yaml
- name: TensorReader
  in:
    fileName: "EigenEnergies.yaml"
  out:
    tensor: EigenEnergies
#+end_src

In the following step we include two further algorithm calls that are necessary
to process the {{{CV}}} and [[id:EigenEnergies][EigenEnergies]]
tensors in =Cc4s= and prepare them for coupled-cluster calculations. To this end the =cc4s.in= file calls the
[[id:DefineHolesAndParticles][DefineHolesAndParticles]] and
[[id:SliceOperator][SliceOperator]] algorithms as described below

#+begin_src yaml
- name: DefineHolesAndParticles
  in:
    eigenEnergies: EigenEnergies
  out:
    slicedEigenEnergies: EigenEnergies

- name: SliceOperator
  in:
    slicedEigenEnergies: EigenEnergies
    operator: CoulombVertex
  out:
    slicedOperator: CoulombVertex
#+end_src

Note that the above algorithms overwrite the original tensors stored in
{{{CV}}} and [[id:EigenEnergies][EigenEnergies]],
turning them into objects corresponding to sets of tensors with partitioned orbital indices, respectively.
In particular, all state indices have been partitioned to refer to particle or hole states; for example,
$\epsilon_q \rightarrow \{\epsilon_a, \epsilon_i\}$.
Using these outputs, we call the [[id:VertexCoulombIntegrals][VertexCoulombIntegrals]]
algorithm by including the following paragraph in the  =cc4s.in= file
#+begin_src yaml
- name: VertexCoulombIntegrals
  in:
    slicedCoulombVertex: CoulombVertex
  out:
    coulombIntegrals: CoulombIntegrals
#+end_src

The [[id:VertexCoulombIntegrals][VertexCoulombIntegrals]] algorithm generates the [[id:CoulombIntegrals][CoulombIntegrals]] as output, which serve as input to the
[[id:CoupledCluster][CoupledCluster]] algorithm and is called using the following code block in  =cc4s.in=

#+begin_src yaml
- name: CoupledCluster
  in:
    method:
      type: Ccsd
      integralsSliceSize: 100
    slicedEigenEnergies: EigenEnergies
    coulombIntegrals: CoulombIntegrals
    slicedCoulombVertex: CoulombVertex
    maxIterations: 30
    energyConvergence: 1.0E-5
    amplitudesConvergence: 1.0E-5
    mixer:
      type: DiisMixer
      maxResidua: 5
  out:
    amplitudes: Amplitudes
#+end_src

If all code blocks given above are included in the =cc4s.in= file and all other prerequisites are fulfilled,
=Cc4s= can be called by typing the following command in the terminal:
#+begin_src sh
mpirun -np 48 Cc4s -i cc4s.in
#+end_src
In the present example we run the calculations in parallel using 48 compute cores.

If all algorithms work successfully, the following output stream will appear on the terminal
#+begin_src sh
                __ __      
     __________/ // / _____
    / ___/ ___/ // /_/ ___/
   / /__/ /__/__  __(__  ) 
   \___/\___/  /_/ /____/  
  Coupled Cluster for Solids

version: heads/develop-0-g3c7f382, date: Fri Dec 17 16:11:36 2021 +0100
build date: Dec 21 2021 18:00:10
compiler: icc (ICC) 19.1.0.166 20191121
total processes: 48
calculation started on: Wed Dec 22 19:47:55 2021


execution plan read, steps: 6

step: 1, TensorReader
Reading from binary file CoulombVertex.dat
realtime 0.078560298 s
--
step: 2, TensorReader
Reading from text file EigenEnergies.dat
realtime 0.003298238 s
--
step: 3, DefineHolesAndParticles
number of holes     No: 16
number of particles Nv: 80
number of states    Np: 96
realtime 0.000931083 s
--
step: 4, SliceOperator
Slicing CoulombVertex.dat into holes and particles.
realtime 0.000822282 s
--
step: 5, VertexCoulombIntegrals
number of field variables NF: 356
realtime 0.003224221 s
--
step: 6, CoupledCluster
Using method Ccsd. integralsSliceSize: 100
Using mixer DiisMixer. maxResidua: 5
Maximum number of iterations: 30
Unless reaching energy convergence dE: 1e-05
and amplitudes convergence dR: 1e-05
Iter         Energy         dE           dR         time   GF/s/core
   1  -2.43605043e+01  -2.4361e+01   4.3924e-01      0.2    2.5
   2  -2.47577534e+01  -3.9725e-01   7.4733e-02      1.3    3.1
   3  -2.53776918e+01  -6.1994e-01   1.8674e-02      1.1    3.4
   4  -2.54455925e+01  -6.7901e-02   6.4132e-03      1.1    3.5
   5  -2.54445080e+01   1.0845e-03   2.2120e-03      1.1    3.5
   6  -2.54458312e+01  -1.3232e-03   1.0304e-03      1.1    3.5
   7  -2.54448941e+01   9.3705e-04   5.0727e-04      1.1    3.5
   8  -2.54452894e+01  -3.9521e-04   1.9694e-04      1.1    3.5
   9  -2.54454262e+01  -1.3682e-04   7.7180e-05      1.1    3.5
  10  -2.54455328e+01  -1.0663e-04   3.0247e-05      1.1    3.5
  11  -2.54455929e+01  -6.0110e-05   1.1758e-05      1.1    3.5
  12  -2.54456151e+01  -2.2218e-05   5.0053e-06      1.1    3.5
  13  -2.54456249e+01  -9.7454e-06   2.2689e-06      1.1    3.5

CCSD correlation energy:          -25.4456248862
2nd-order correlation energy:     -24.3605043096
realtime 13.653374348 s
--
total realtime: 13.753230265 s
total operations: 2267.4 GFLOPS, speed: 3.4 GFLOPS/s/core
#+end_src

The CCSD correlation energy can either be extracted
directly from the standard output stream or the =cc4s.out= YAML file, which contains additional information as well
as the correlation energy. The corresponding block of =cc4s.out= reads
#+begin_src yaml
    out:
      amplitudes: 0x2682218
      convergenceReached: 1
      energy:
        direct: -38.822491455744313
        exchange: 13.376866569541551
        secondOrder: -24.360504309639897
        unit: 0.036749322175638782
        correlation: -25.445624886202761
#+end_src
Note that the energies are given in units of eV for the present system. The energy units are defined by
input files and always correspond to eV in the case of input files generated by =VASP=.

* Perturbative triples calculations

We now proceed with the CCSD(T) energy calculation and seek to compute the (T) contribution,
which has to be added to the CCSD correlation energy contribution estimated in the
previous section.

The [[id:PerturbativeTriples][PerturbativeTriples]] algorithm computes the (T)
correlation energy contribution and is called from the =cc4s.in= file in the following manner

#+begin_src yaml
- name: PerturbativeTriples
  in:
    slicedEigenEnergies: EigenEnergies
    amplitudes: Amplitudes
    coulombIntegrals: CoulombIntegrals
  out:
    {}
#+end_src

Note that the  [[id:PerturbativeTriples][PerturbativeTriples]] algorithm depends on [[id:Amplitudes][Amplitudes]]
as input argument which has been computed above using the
[[id:CoupledCluster][CoupledCluster]] algorithm. 
If we append the above code block to the =cc4s.in= file described in the previous section and run =Cc4s=,
the following additional standard output stream should appear.
#+begin_src sh
--
step: 7, PerturbativeTriples
Progress(%)  time(s)   GFLOP/s      
1            0         3.850        
10           0         5.376        
20           0         5.531        
30           0         5.625        
40           0         5.618        
50           0         5.643        
60           0         5.664        
70           0         5.696        
80           0         5.704        
90           0         5.731        
100          0         5.730        
(T) correlation energy:      -0.822530510989498
realtime 2.855223959 s
--
#+end_src

The (T) correlation energy contribution can either be extracted
directly from the standard output stream or the =cc4s.out= YAML file, which contains additional information as well
as the correlation energy contribution. The corresponding block of =cc4s.out= reads
#+begin_src yaml
    name: PerturbativeTriples
    out:
      energy:
        triples: -0.82253051098949814
    realtime: 2.856075204
#+end_src

* Basis-set incompleteness error correction

We note that in the present case, the CCSD correlation energy is computed using a set of truncated
approximate natural orbitals. Increasing this basis set size yields correlation energies that
converge only slowly to the complete basis set limit. =Cc4s= includes an algorithm that can compute
a basis-set incompleteness error (BSIE) correction, yielding significantly more rapidly convergent correlation
energies with respect to the number virtual orbitals.

The [[id:CcsdFocalPointBasisSetCorrection][CcsdFocalPointBasisSetCorrection]] computes a BSIE correction for
CCSD theory and requires a set of additional input files that are also provided using the =VASP= interface.
Reading the corresponding input files and calling the
[[id:CcsdFocalPointBasisSetCorrection][CcsdFocalPointBasisSetCorrection]] algorithm is achieved using the
following code block in =cc4s.in=
#+begin_src yaml
- name: TensorReader
  in:
    fileName: "DeltaIntegralsHH.yaml"
  out:
    tensor: Nij

- name: TensorReader
  in:
    fileName: "DeltaIntegralsPPHH.yaml"
  out:
    tensor: DeltaIntegrals

- name: TensorReader
  in:
    fileName: "Mp2PairEnergies.yaml"
  out:
    tensor: Mp2PairEnergies

- name: CcsdFocalPointBasisSetCorrection
  in:
    slicedEigenEnergies: EigenEnergies
    amplitudes: Amplitudes
    coulombIntegrals: CoulombIntegrals
    mp2PairEnergies: Mp2PairEnergies
    deltaIntegralsHH: Nij
    deltaIntegralsPPHH: DeltaIntegrals
  out:
    {}
#+end_src

Appending the code block above to the =cc4s.in= file described in all previous sections and running =Cc4s=,
yields the following additional standard output stream.
#+begin_src sh
--
step: 8, TensorReader
Reading from text file DeltaIntegralsHH.dat
realtime 0.011865465 s
--
step: 9, TensorReader
Reading from binary file DeltaIntegralsPPHH.dat
realtime 0.063157853 s
--
step: 10, TensorReader
Reading from text file Mp2PairEnergies.dat
realtime 0.016661099 s
--
step: 11, CcsdFocalPointBasisSetCorrection
CCSD correlation energy:          -25.4456248862
CCSD-FP correlation energy:       -30.7454273364
2nd-order-CBS correlation energy: -30.8616919387
==================================
CCSD-BSIE energy correction:      -5.2998024502
2nd-order energy correction :     -6.5011876290
PS-PPL-BSIE energy correction:    1.2013851788
realtime 0.079432832 s
--
#+end_src

The BSIE correction can either be extracted
directly from the standard output stream or the =cc4s.out= YAML file, which contains additional information as well
as the correction. The corresponding block of =cc4s.out= reads
#+begin_src yaml
????
#+end_src

* Finite-size correction

In the present example the CCSD correlation energy is computed for a finite periodic simulation cell.
Increasing the size of the employed periodic simulation cell
yields correlation energies per atom that converge only slowly to the thermodynamic limit.
=Cc4s= includes an algorithm that can compute
a finite-size error correction, yielding significantly more rapidly convergent correlation
energies per atom with respect to the simulation cell size.

The [[id:TransitionStructureFactorFiniteSizeCorrection][TransitionStructureFactorFiniteSizeCorrection]] algorithm computes
a finite-size correction for CCSD theory and requires a set of additional input files that are also
provided by the =VASP= interface.
Reading the corresponding input files and calling the
[[id:TransitionStructureFactorFiniteSizeCorrection][TransitionStructureFactorFiniteSizeCorrection]]
algorithm is achieved using the following code block in =cc4s.in=
#+begin_src yaml
- name: TensorReader
  in:
    fileName: "CoulombVertexSingularVectors.yaml"
  out:
    tensor: CoulombVertexSingularVectors

- name: TensorReader
  in:
    fileName: "GridVectors.yaml"
  out:
    tensor: GridVectors

- name: TensorReader
  in:
    fileName: "CoulombPotential.yaml"
  out:
    tensor: CoulombPotential

- name: TransitionStructureFactorFiniteSizeCorrection
  in:
    slicedCoulombVertex: CoulombVertex
    amplitudes: Amplitudes
    coulombVertexSingularVectors: CoulombVertexSingularVectors
    coulombPotential: CoulombPotential
    gridVectors: GridVectors
  out:
    corrected: Corrected
    uncorrected: Uncorrected
    transitionStructureFactor: SF
#+end_src

Appending the code block above to the =cc4s.in= file described in all previous sections and running =Cc4s=,
yields the following additional standard output stream.
#+begin_src sh
--
step: 12, TensorReader
Reading from binary file CoulombVertexSingularVectors.dat
realtime 0.009562659 s
--
step: 13, TensorReader
Reading from text file GridVectors.dat
realtime 0.003062648 s
--
step: 14, TensorReader
Reading from text file CoulombPotential.dat
realtime 0.002374490 s
--
step: 15, TransitionStructureFactorFiniteSizeCorrection
Uncorrected correlation energy:   -25.4453762360
Finite-size energy correction:    -1.1152868081
realtime 0.452425713 s
--
#+end_src

The finite-size correction can either be extracted
directly from the standard output stream or the =cc4s.out= YAML file, which contains additional information as well
as the correction. The corresponding block of =cc4s.out= reads
#+begin_src yaml
TODO
#+end_src

* Final energy

We now discuss how to combine all energy contributions from above to obtain the final estimate of the
ground state energy in the thermodynamic and complete basis-set limit.
The table below summarizes all computed ground state energy contributions for the present example.

#+caption: Ground state energy summary for present example. All energies in eV.
#+name: energy-output
| Contribution                 | Value                             |
|------------------------------+-----------------------------------|
| Hartree--Fock                |  -116.426066                      |
| CCSD correlation             |  -25.445625                       |
| (T)  correlation             |  -0.822531                        |
| CCSD BSIE energy correction  |  -5.299802                        |
| CCSD finite-size energy correction  |  -1.115287                 |
|------------------------------+-----------------------------------|
| =CCSD(T) energy + corrections= |  -149.109311                      |
|------------------------------+-----------------------------------|

Please note that the Hartree--Fock energy contribution was obtained using the preceeding =VASP= calculation. We recommend to
converge the Hartree--Fock energy contribution to the thermodynamic limit separately using denser $k$ -meshes if necessary.
The final =CCSD(T) energy + corrections= value can be used to study all accessible physical properties of interest.

