:PROPERTIES:
:ID: BasisSetCorrection
:END:
#+title: =BasisSetCorrection=
#+OPTIONS: toc:nil

* Brief description
This algorithm evaluates a correction to the basis-set-incompeteness error (BSIE) of CCSD correlation energies.
* Algorithm call

A typical input file snippet to call the =BasisSetCorrection= algorithm is given below.

#+begin_src yaml
- name: BasisSetCorrection
  in:
    slicedEigenEnergies: EigenEnergies
    amplitudes: Amplitudes
    coulombIntegrals: CoulombIntegrals
    mp2PairEnergies: Mp2PairEnergies
    deltaIntegralsHH: DeltaIntegralsHH
    deltaIntegralsPPHH: DeltaIntegralsPPHH
  out:
    {}
#+end_src


* Algorithm input

#+caption: Input keywords
#+name: focalpoint-input-table
| Keyword               | Value                          |
|-----------------------+--------------------------------|
| =amplitudes=          | [[id:Amplitudes][Singles and doubles amplitudes]] |
| =deltaIntegralsPPHH=  | [[id:DeltaIntegrals][DeltaIntegrals]]   |
| =deltaIntegralsHH=    | [[id:DeltaIntegrals][DeltaIntegrals]]   |
| =mp2PairEnergiese=    | [[id:Mp2PairEnergies][MP2 pair energies matrix]]       |
| =coulombIntegrals=    | [[id:CoulombIntegrals][Coulomb Integrals]]              |
| =slicedEigenEnergies= | [[id:SlicedEigenEnergies][Sliced one-electron energies]]   |


* Algorithm output

The output of the algorithm is the CCSD BSIE correction. This energy contains
the 2nd-order energy correction and a pair-specific contribution that accounts for the BSIE of the particle-particle ladder term (see theory).

** Sample =stdout=
Below an example standard output stream is shown for a successful run.
#+begin_src sh
step: 10, BasisSetCorrection
Ccsd-BSIE energy correction:      -0.0165423958
#+end_src

* Sample =yaml= output

Below an example =yaml= output stream is shown for a successful run.

#+begin_src yaml
    name: BasisSetCorrection
    out:
      energy:
        correction: -5.2998024502064709
        pplCorrection: 1.2013851788124801
        secondOrderCorrection: -6.5011876290189505
        uncorrectedCorrelation: -25.445624886202786
        unit: 0.036749322175638782
    realtime: 0.080797438
#+end_src


* Computational complexity

This algorithm is a post-processing algorithm. However, the 2nd-order
energy is re-evaluated and other operations of the same computational
complexity are performed. The memory footprint is also in the order of a 2nd-order
energy calculation.


* Theory

This algorithm evaluates a correction to the basis-set-incompleteness error (BSIE)
of CCSD correlation energies as descibed in Ref. cite:&FocalPointAppIrmler2021. The algorithm
requires the converged CCSD amplitudes together with [[id:DeltaIntegrals][\delta-integrals]]. Futhermore,
a complete-basis-set-limit estimate of the [[id:Mp2PairEnergies][MP2 pair-correlation-energies]] is needed.

As discussed in  Ref. cite:&FocalPointAppIrmler2021, the CCSD-BSIE in a finite basis-set
calculation is primarily due to the 2nd-order term, and the so-called
particle-particle ladder (ppl) term. 
There exists a variety of algorithms which allow
a reliable CBS estimate for the 2nd-order term at modest computational costs
(compared to a the corresponding CCSD calculation for the same system). The
missing ppl BSIE contribution is approximated using a pair-specific expression
which requires the [[id:Mp2PairEnergies][MP2 pair-correlation-energies]],
CCSD amplitudes, as-well-as the [[id:DeltaIntegrals][\delta-integrals]].
The implemented ppl-correction is defined by Eq.(31) in Ref. cite:&FocalPointAppIrmler2021 .
The provided CCSD-BSIE energy correction is the sum of the 2nd-order energy
correction and the ppl-correction-term.


* Literature
bibliography:../group.bib


