:PROPERTIES:
:ID: common-inputs
:END:
#+title: Common inputs for =cc4s= algorithms

This page describes common input variables used
consistently in the same way in several algorithms in =cc4s=.

* Inputs
** amplitudes
:PROPERTIES:
:CUSTOM_ID: amplitudes
:END:

The =amplitudes= keyword requires the singles and doubles amplitudes as input.
These amplitudes can be obtained using the [[id:CoupledCluster][*CoupledCluster*]] algorithm.

** TODO coulombIntegrals
:PROPERTIES:
:CUSTOM_ID: coulombintegrals
:END:

#+begin_todo
Add algorithm link to VertexCoulombIntegrals
#+end_todo

The =coulombIntegrals= keyword requires a set of two-electron
integrals $V_{ab}^{ij}$, ... as input.
~CoulombIntegrals~ is generated by the *VertexCoulombIntegrals* algorithm.

** TODO slicedEigenEnergies
:PROPERTIES:
:CUSTOM_ID: slicedeigenenergies
:END:

#+begin_todo
put a link to DefineHolesAndParticles
#+end_todo

The =slicedEigenEnergies= keyword requires a sliced input tensor corresponding to one-electron Hartree--Fock energies $\epsilon_p$
of hole ($\epsilon_p$) and particle ($\epsilon_a$) states as input.
The sliced input tensor is generated by the *DefineHolesAndParticles* algorithm.
