:PROPERTIES:
:ID: CoupledCluster
:END:
#+title: =CoupledCluster=
#+OPTIONS: toc:nil

* Brief description
This algorithm solves the CCSD amplitude equations using the Coulomb integrals
and Hartree--Fock eigenenergies.
* Algorithm call

A typical input file snippet to call the =CoupledCluster= algorithm is given below.
#+begin_src yaml :noweb yes
- name: CoupledCluster
  in:
    method:
      type: Ccsd
      integralsSliceSize: 100
    slicedEigenEnergies: EigenEnergies
    coulombIntegrals: CoulombIntegrals
    slicedCoulombVertex: CoulombVertex
    maxIterations: 20
    energyConvergence: 1.0E-4
    amplitudesConvergence: 1.0E-4
    mixer:
      type: DiisMixer
      maxResidua: 5
    #or for instance a linear mixer
    #mixer:
    #  type: LinearMixer
    #  ratio: 1.0
  out:
    amplitudes: Amplitudes
#+end_src

* Algorithm input

#+caption: Input keywords
#+name: ccsd-input-table
| Keyword                      | Value                             |
|------------------------------+-----------------------------------|
| =method: type=               | [[#method-type][Type of coupled cluster algorithm]] |
| =method: integralsSliceSize= | [[#integralsslicesize][Integral slice size]]               |
| =slicedEigenEnergies=        | [[id:SlicedEigenEnergies][Sliced one-electron energies]]      |
| =coulombIntegrals=           | [[id:CoulombIntegrals][Coulomb Integrals]]                 |
| =slicedCoulombVertex=        | [[id:SlicedCoulombVertex][Sliced Coulomb vertex]]             |
| =maxIterations=              | [[#maxiterations][Maximum number of iterations]]      |
| =energyConvergence=          | [[#energyconvergence][Energy convergence threshold]]      |
| =amplitudesConvergence=      | [[#amplitudesconvergence][Amplitude convergence threshold]]   |
| =mixer: type=                | [[#mixer][Mixer type]]                        |
|------------------------------+-----------------------------------|

** type
:PROPERTIES:
:CUSTOM_ID: method-type
:END:
=method: type= specifies the  coupled-cluster approximation for the amplitudes to be used.
The currently available approximations are:
  - =Ccsd= :: Coupled Cluster singles and doubles [[cite:&Bartlett2007-cm]].
  - =CcsdReference= :: Canonical and unoptimized version of the =Ccsd= algorithm.
    This algorithm has the same inputs as =Ccsd= with the exception of the
    [[#integralsslicesize][integralSliceSize]] input argument.
  - =Drccsd= :: Direct-Ring Coupled Cluster singles and doubles [[cite:&paier2012assessment]].

** integralsSliceSize
:PROPERTIES:
:CUSTOM_ID: integralsslicesize
:END:

=integralsSliceSize= controls the slice size of the $V_{cd}^{ab}$ integrals, which are computed on-the-fly to
reduce the memory footprint. The integer value specified for =integralsSliceSize=  refers to the dimension size
used for the $a$ and $b$ index. We recommend setting =integralsSliceSize: 100= to balance
computational efficency with memory usage. Smaller/larger values reduce/increase the memory footprint.

** maxIterations
:PROPERTIES:
:CUSTOM_ID: maxiterations
:END:

=maxIterations= controls the maximum number of iterations allowed to solve the  $t_{ij}^{ab}$ and $t_i^a$ amplitude equations.
If convergence of the energy and residual vectors within the specified thresholds is achieved using fewer iterations
than =maxIterations=, the algorithm was successfull and will stop.
If =maxIterations= is reached without achieving =energyConvergence= and =amplitudesConvergence= , the algorithm was not
successful and will stop. We recommend to set =maxIterations: 20=, which is ususally enough to achieve reasonable convergence
thresholds.

** energyConvergence
:PROPERTIES:
:CUSTOM_ID: energyconvergence
:END:

=energyConvergence= specifies the convergence threshold for the correlation energy.
If =energyConvergence= and =amplitudesConvergence= is achieved, the iterative solution was successful and the algorithm will stop.

** amplitudesConvergence
:PROPERTIES:
:CUSTOM_ID: amplitudesconvergence
:END:

=amplitudesConvergence= specifies the convergence threshold for the residual vector of the singles and doubles amplitude equations.
If =energyConvergence= and =amplitudesConvergence= is achieved, the iterative solution was successful and the algorithm will stop.

** mixer
:PROPERTIES:
:CUSTOM_ID: mixer
:END:

=mixer= specifies mixer-specific parameters used to solve the amplitude equations iteratively.
The direct inversion iterative subspace (Diis) algorithm is the default algorithm used to mix amplitude guesses from previous
iterations to improve the guess for the next iteration.
=mixer: type= can currently be set to =*DiisMixer= or =*LinearMixer=.

*** DiisMixer
For =mixer: type: DissMixer=, it is possible to specify =mixer: maxResidua=, which controls the number of residual
vectors used by the Diis mixer.
We recommend to set the maximum number of residual vectors used in the =DiisMixer= to =5=.
More residual vectors result in a larger memory footprint.

- Example ::
#+begin_src yaml
mixer:
  type: DiisMixer
  maxResidua: 5
#+end_src


*** LinearMixer

For =mixer: type: LinearMixer= it is possible to specify =mixer: ratio=, which controls the mixing ratio used
to update the new guess of the amplitudes based on estimates from the previous and current iteration.
The =LinearMixer= exhibits the smallest possible memory footprint from all currently available mixers,
keeping two sets of amplitudes in memory at once only.
We recommend to set =mixer: ratio: 1.0=. Smaller ratios result in a slower but perhaps more stable convergence.

- Example ::
#+name: linear-mixer-example
#+begin_src yaml
mixer:
  type: LinearMixer
  ratio: 1.0
#+end_src

* Algorithm output

#+caption: Output keywords for CoupledCluster
#+name: ccsd-output-table
| Keyword      | Value      |
|--------------+------------|
| =amplitudes= | [[id:Amplitudes][Amplitudes]] |
|--------------+------------|

The output of the *CoupledCluster* algorithm includes =energy= and =amplitudes= . The =amplitudes= output contains
the converged singles and doubles amplitude tensors. The amplitudes can be used as input for algorithms
that estimate the finite simulation cell size error (*TransitionStructureFactorFiniteSizeCorrection*)
and the basis set incompleteness errors (*CcsdFocalPointBasisSetCorrection*).

** Sample =stdout=
Below an example standard output stream is shown for a successful *CoupledCluster* algorithm run.
#+begin_src sh
step: 9, CoupledCluster
Using method Ccsd. integralsSliceSize: 96
Using mixer DiisMixer. maxResidua: 5
Maximum number of iterations: 30
Unless reaching energy convergence dE: 0.0001
and amplitudes convergence dR: 0.0001
Iter         Energy         dE           dR         time   GF/s/core
   1  -1.51995933e+02  -1.5200e+02   1.0108e+00     32.6    5.6
   2  -1.48908010e+02   3.0879e+00   1.8077e-01    381.6    9.3
   3  -1.51620340e+02  -2.7123e+00   3.8331e-02    381.7    9.3
   4  -1.52039881e+02  -4.1954e-01   1.2254e-02    380.1    9.3
   5  -1.52001191e+02   3.8690e-02   2.6566e-03    381.7    9.3
   6  -1.51996162e+02   5.0293e-03   9.0534e-04    381.3    9.3
   7  -1.51998504e+02  -2.3416e-03   2.6783e-04    382.1    9.3
   8  -1.51997751e+02   7.5305e-04   8.5906e-05    383.2    9.2
   9  -1.51998116e+02  -3.6568e-04   2.4672e-05    380.0    9.3
  10  -1.51998173e+02  -5.7065e-05   9.5722e-06    376.6    9.4

Ccsd correlation energy:          -151.9981733061
2nd-order correlation energy:     -151.9959332292
realtime 3463.773373
#+end_src

** TODO Sample =yaml= output

* Computational complexity

This section contains computational or memory footprints
for the various methods implemented in *CoupledCluster*
[[#method-type][(see type)]].

** =Ccsd method=
The computational bottle neck of a typical Ccsd calculation originates from the following contraction, which is
part of the doubles amplitude equations: $V_{cd}^{ab} t_{ij}^{cd}$. The computational cost for evaluating this expression scales
as $\mathcal{O}(N_{\rm o}^2 N_{\rm v}^4)$. To avoid a memory footprint of $\mathcal{O}(N_{\rm v}^4)$ in storing
$V_{cd}^{ab}$, slices $V_{cd}^{xy}$ are computed on-the-fly and used in the contraction, reducing
the corresponding memory footprint to $\mathcal{O}(N_{\rm v}^2 N_{\rm s}^2)$, where $N_{\rm s}$ is controlled using
the =integralsSliceSize= keyword.

We note that required storage of a set of doubles amplitudes adds substantially to the memory footprint in Ccsd calculations.
The Diis algorithm requires the storage of both doubles residua and amplitudes =maxResidua= times. We recommend to choose the
type of mixer and its parameters carefully to reduce the memory fottprint if necessary.

** TODO =Drccd method=

* Theory

We recommend the following review article and references therein to get started with coupled-cluster theory cite:&Bartlett2007-cm .

* Literature
bibliography:../group.bib


