:PROPERTIES:
:ID: PerturbativeTriples
:END:
#+title: =PerturbativeTriples=
#+OPTIONS: toc:nil

* Brief description
Evaluates the (T) contribution.
* Algorithm call

A typical input file snippet to call the =PerturbativeTriples= algorithm is given below.

#+begin_src yaml
- name: PerturbativeTriples
  in:
    coulombIntegrals: CoulombIntegrals
    amplitudes: Amplitudes
    slicedEigenEnergies: EigenEnergies
    mp2PairEnergies: Mp2PairEnergies
  out:
    {}
#+end_src


* Algorithm input

#+caption: Input keywords for PerturbativeTriples
| Keyword               | Value                          |
|-----------------------+--------------------------------|
| =amplitudes=          | [[id:Amplitudes][Singles and doubles amplitudes]] |
| =coulombIntegrals=    | [[id:CoulombIntegrals][Coulomb Integrals]]              |
| =slicedEigenEnergies= | [[id:SlicedEigenEnergies][Sliced one-electron energies]]   |
| =mp2PairEnergies=     | [[id:Mp2PairEnergies][MP2 pair energies matrix]]       |


* Algorithm output


** Sample =stdout=
Below an example standard output stream is shown for a successful =PerturbativeTriples= algorithm run
given a =mp2pairenergies= and thus printing the CCSD(T*) energy.


#+begin_src sh
step: 15, PerturbativeTriples
Progress(%)  time(s)   GFLOP/s
1            334       6.027        
10           2334      6.327        
20           2323      6.342        
30           2330      6.341        
40           2282      6.373        
50           2286      6.390        
60           2282      6.404        
70           2279      6.415        
80           2279      6.423        
90           2324      6.415        
100          2329      6.408        
(T) correlation energy:      -4.822365952756229
(T*) correlation energy:      -4.965491965438498
realtime 23297.807220394 s
#+end_src

** TODO Sample =yaml= output

* Computational complexity

The computational cost is $\mathcal{O}{(N_o^3 N_v^3(N_o+N_v))}$ with $N_o$ and 
$N_v$ being the number of occupied and virtual orbitals, respectively. The memory
footprint is mainly determined by the storage of the PPPH-integral, which is of 
size $\mathcal{O}{N_o N_v^3}$.
* Theory

The implemented expressions of (T) correspond to those from Ref. [[cite:&RAGHAVACHARI1989479]]. For more details see Ref. [[cite:&Bartlett2007-cm]] and references therin. 

* Reference implementation

In addition to the =PerturbativeTriples= algorithm, there is also a slower
reference implementation called =PerturbativeTriplesReference= which
is used in the same way as =PerturbativeTriples=.
To use it, you should just change the name =PerturbativeTriples= by =PerturbativeTriplesReference=.

* Literature
bibliography:../group.bib
