#+title: =TransitionStructureFactorFiniteSizeCorrection= Algorithm

* Example yaml input

A typical input file snippet of =cc4s.in=  to call the *TransitionStructureFiniteSizeCorrection* algorithm is given below.
#+begin_src yaml
- name: TransitionStructureFactorFiniteSizeCorrection
  in:
    slicedCoulombVertex: CoulombVertex
    amplitudes: Amplitudes
    coulombVertexSingularVectors: CoulombVertexSingularVectors
    coulombPotential: CoulombPotential
    gridVectors: GridVectors
  out:
    transitionStructureFactor: SF
    corrected: Corrected
    uncorrected: Uncorrected
#+end_src

* Input description

#+caption: Input keywords for CoupledCluster
#+name: ccsd-input-table
| Input Keyword                  | Description                    | Default |
|--------------------------------+--------------------------------+---------|
| =slicedCoulombVertex=          | [[#slicedcoulombvertex][Sliced Coulomb vertex]]          |         |
| =amplitudes=                   | [[../common-inputs.org::#amplitudes][Singles and doubles amplitudes]] |         |
| =coulombVertexSingularVectors= | [[#coulombvertexsingularvectors][coulombVertexSingularVectors]]   |         |
| =coulombPotential=             | [[#coulombpotential][Coulomb potential]]              |         |
| =gridVectors=                  | [[#gridvectors][Grid Vectors]]                   |         |
| =interpolationGridSize=        | [[#interpolationgridsize][Interpolation grid size]]        |      20 |
|--------------------------------+--------------------------------+---------|

** slicedCoulombVertex
:PROPERTIES:
:CUSTOM_ID: slicedcoulombvertex
:END:

The =slicedCoulombVertex= keyword requires the Coulomb vertex $\Gamma_{pG}^r$ as input.
The Coulomb vertex is used to compute two-electron integrals $V_{ij}^{ab}$ and can be
generated by the *SliceOperator* algorithm.

** TODO amplitudes
:PROPERTIES:
:CUSTOM_ID: amplitudes
:END:

#+begin_todo
think about including or just referencing
#+end_todo

#+include: ../common-inputs.org::#amplitudes :only-contents t

** coulombVertexSingularVectors
:PROPERTIES:
:CUSTOM_ID: coulombvertexsingularvectors
:END:

The =coulombVertexSingularVectors= keyword requires the transformation from the auxiliary-field basis to the plane-wave basis $U_{G}^{F}$ as input.
This transformation matrix should be read in from an external file using the *TensorReader* algorithm.

** coulombPotential
:PROPERTIES:
:CUSTOM_ID: coulombpotential
:END:

The =coulombPotential= keyword requires the Coulomb potential in a plane-wave basis set representation $\tilde{v}(G)$ as input.
The Coulomb potential has to agree with the one employed for the calculation of the Coulomb vertex.
The Coulomb potential should be read in from an external file using the *TensorReader* algorithm.

** gridVectors
:PROPERTIES:
:CUSTOM_ID: gridvectors
:END:

The =gridVectors= keyword requires the grid vectors of the emplyoed plane-wave basis $\{ G_1, ...,G_n \}$ as input.
The set of grid vectors should be read in from an external file using the *TensorReader* algorithm.

** interpolationGridSize
:PROPERTIES:
:CUSTOM_ID: interpolationgridsize
:END:

The =interpolationGridSize= keyword can be used to control the finesness of the grid used to interpolate the
electronic transition structure factor in each spatial direction.
A value of $N$ for the =interpolationGridSize= means that $2 N$ sampling points are used to sample the interpolated structure factor in each direction.


* Output

#+caption: Output keywords for CoupledCluster
#+name: ccsd-output-table
| Output Keyword              | Description                  |
|-----------------------------+------------------------------|
| =transitionStructureFactor= | Transition Structure factor  |
| =energy=                    | finite size corrected energy |
|-----------------------------+------------------------------|

The output of the *TransitionStructureFactorFiniteSizeCorrection* algorithm includes transition structure factor $S(G)$ and
an estimate of the finitie size error correction to the correlation energy. The finite size error is estimated using a tricubic interpolation
algorithm of the electronic transition structure factor.

Below an example standard output stream is shown for a successful *TransitionStructureFactorFiniteSizeCorrection* algorithm run.
#+begin_src sh
step: 10, TransitionStructureFactorFiniteSizeCorrection
Uncorrected correlation energy:   -171.7706873818
Finite-size energy correction:    -0.8222012413
realtime 68.117389991 s
#+end_src

* Computational Complexity and memory footprint

No considerable memory footprints or computational cost bottle necks are expected for this algorithm compared. 

* Theory

The methods employed in this algorithm are discussed in Refs. cite:&liao2016communication and cite:&gruber2018applying .
We employ a tricubic interpolation technique to reduce
quadrature errors in the numerical expression of the electronic correlation energy: $\sum_{ G}S({ G}){\tilde{v}}({ G})$.
In particular, the quadrature errors around ${G}=0$ are large and result in significant finite-size errors for small simulation cells.
In order to obtain a more accurate estimate of the correlation energy in the thermodynamic limit,
we proceed as follows.
We introduce additional sampling points at an arbitrarily dense
grid, which we choose to be $2N\times 2N \times 2N$ times denser than the original one.
The interpolated transition structure factor and the analytic expression of the Coulomb kernel can be used
to calculate the correlation energy with the usual expression given above.
The difference between the correlation energies computed with the interpolated and non-interpolated structure factor
yields an estimate of the finite correction to the electronic correlation energy that is returned by this algorithm.
We find that $N=20$ yields well converged correlation energies for sufficiently large unit cells.
However, we recommend to check convergence with respect to this parameter for each system separetely.

* Literature
bibliography:../../group.bib


